
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.26100 - AMD64
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CheckCXXCompilerFlag.cmake:55 (cmake_check_compiler_flag)"
      - "thirdParty/ozz-animation/build-utils/cmake/compiler_settings.cmake:83 (check_cxx_compiler_flag)"
      - "thirdParty/ozz-animation/CMakeLists.txt:40 (include)"
    checks:
      - "Performing Test W_IGNORED_ATTRIBUTES"
    directories:
      source: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-s73yq5"
      binary: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-s73yq5"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "D:/MyGame/build/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "W_IGNORED_ATTRIBUTES"
      cached: true
      stdout: |
        Change Dir: 'D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-s73yq5'
        
        Run Build Command(s): D:/ninja-win/ninja.exe -v cmTC_f645d
        [1/2] D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat -DW_IGNORED_ATTRIBUTES  -std=c++17   -Wignored-attributes -MD -MT CMakeFiles/cmTC_f645d.dir/src.cxx.o -MF CMakeFiles\\cmTC_f645d.dir\\src.cxx.o.d -o CMakeFiles/cmTC_f645d.dir/src.cxx.o -c D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-s73yq5/src.cxx
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat   CMakeFiles/cmTC_f645d.dir/src.cxx.o -o cmTC_f645d.js   && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CheckCXXCompilerFlag.cmake:55 (cmake_check_compiler_flag)"
      - "thirdParty/ozz-animation/build-utils/cmake/compiler_settings.cmake:90 (check_cxx_compiler_flag)"
      - "thirdParty/ozz-animation/CMakeLists.txt:40 (include)"
    checks:
      - "Performing Test W_98_COMPAT_PEDANTIC"
    directories:
      source: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-2n74b2"
      binary: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-2n74b2"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "D:/MyGame/build/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "W_98_COMPAT_PEDANTIC"
      cached: true
      stdout: |
        Change Dir: 'D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-2n74b2'
        
        Run Build Command(s): D:/ninja-win/ninja.exe -v cmTC_04263
        [1/2] D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat -DW_98_COMPAT_PEDANTIC  -std=c++17   -Wc++98-compat-pedantic -MD -MT CMakeFiles/cmTC_04263.dir/src.cxx.o -MF CMakeFiles\\cmTC_04263.dir\\src.cxx.o.d -o CMakeFiles/cmTC_04263.dir/src.cxx.o -c D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-2n74b2/src.cxx
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat   CMakeFiles/cmTC_04263.dir/src.cxx.o -o cmTC_04263.js   && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CheckCXXCompilerFlag.cmake:55 (cmake_check_compiler_flag)"
      - "thirdParty/ozz-animation/build-utils/cmake/compiler_settings.cmake:97 (check_cxx_compiler_flag)"
      - "thirdParty/ozz-animation/CMakeLists.txt:40 (include)"
    checks:
      - "Performing Test W_UNUSED_RESULT"
    directories:
      source: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-uha2od"
      binary: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-uha2od"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "D:/MyGame/build/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "W_UNUSED_RESULT"
      cached: true
      stdout: |
        Change Dir: 'D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-uha2od'
        
        Run Build Command(s): D:/ninja-win/ninja.exe -v cmTC_e28a6
        [1/2] D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat -DW_UNUSED_RESULT  -std=c++17   -Wunused-result -MD -MT CMakeFiles/cmTC_e28a6.dir/src.cxx.o -MF CMakeFiles\\cmTC_e28a6.dir\\src.cxx.o.d -o CMakeFiles/cmTC_e28a6.dir/src.cxx.o -c D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-uha2od/src.cxx
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat   CMakeFiles/cmTC_e28a6.dir/src.cxx.o -o cmTC_e28a6.js   && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CheckCXXCompilerFlag.cmake:55 (cmake_check_compiler_flag)"
      - "thirdParty/ozz-animation/build-utils/cmake/compiler_settings.cmake:98 (check_cxx_compiler_flag)"
      - "thirdParty/ozz-animation/CMakeLists.txt:40 (include)"
    checks:
      - "Performing Test W_NULL_DEREFERENCE"
    directories:
      source: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-lhvg5n"
      binary: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-lhvg5n"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "D:/MyGame/build/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "W_NULL_DEREFERENCE"
      cached: true
      stdout: |
        Change Dir: 'D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-lhvg5n'
        
        Run Build Command(s): D:/ninja-win/ninja.exe -v cmTC_885f6
        [1/2] D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat -DW_NULL_DEREFERENCE  -std=c++17   -Wnull-dereference -MD -MT CMakeFiles/cmTC_885f6.dir/src.cxx.o -MF CMakeFiles\\cmTC_885f6.dir\\src.cxx.o.d -o CMakeFiles/cmTC_885f6.dir/src.cxx.o -c D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-lhvg5n/src.cxx
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat   CMakeFiles/cmTC_885f6.dir/src.cxx.o -o cmTC_885f6.js   && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CheckCXXCompilerFlag.cmake:55 (cmake_check_compiler_flag)"
      - "thirdParty/ozz-animation/build-utils/cmake/compiler_settings.cmake:99 (check_cxx_compiler_flag)"
      - "thirdParty/ozz-animation/CMakeLists.txt:40 (include)"
    checks:
      - "Performing Test W_PRAGMA_PACK"
    directories:
      source: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-twg8fs"
      binary: "D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-twg8fs"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "D:/MyGame/build/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules;D:/MyGame/build/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "W_PRAGMA_PACK"
      cached: true
      stdout: |
        Change Dir: 'D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-twg8fs'
        
        Run Build Command(s): D:/ninja-win/ninja.exe -v cmTC_0f713
        [1/2] D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat -DW_PRAGMA_PACK  -std=c++17   -Wpragma-pack -MD -MT CMakeFiles/cmTC_0f713.dir/src.cxx.o -MF CMakeFiles\\cmTC_0f713.dir\\src.cxx.o.d -o CMakeFiles/cmTC_0f713.dir/src.cxx.o -c D:/workspace/MyWebGame/electron-vite-react-opengl-webassembly/src/components/myapp/build_emscripten_debug/CMakeFiles/CMakeScratch/TryCompile-twg8fs/src.cxx
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\MyGame\\build\\emsdk\\upstream\\emscripten\\em++.bat   CMakeFiles/cmTC_0f713.dir/src.cxx.o -o cmTC_0f713.js   && cd ."
        
      exitCode: 0
...
